# Generated by Django 3.0.6 on 2020-06-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='hometown',
            field=models.CharField(default='undefined', max_length=25),
        ),
        migrations.AddField(
            model_name='musician',
            name='photo',
            field=models.CharField(default='undefined', max_length=200),
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
