# Generated by Django 3.0.6 on 2020-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_auto_20200604_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='group',
            field=models.ManyToManyField(help_text='Enter a group for this musician.', to='artist.Group'),
        ),
    ]
