# Generated by Django 3.0.6 on 2020-06-04 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_musician_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_formed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='group',
            name='origin',
            field=models.CharField(default='undefined', max_length=25),
        ),
    ]
