# Generated by Django 3.0.6 on 2020-06-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20200604_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='origin',
            field=models.CharField(default='', max_length=25),
        ),
    ]
