# Generated by Django 3.0.6 on 2020-06-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_auto_20200604_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(help_text='enter musicians.', related_name='_group_members_+', to='artist.Musician'),
        ),
    ]
