# Generated by Django 3.0.6 on 2020-06-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_auto_20200608_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='about',
            field=models.CharField(default="The genre's description goes here. ", max_length=300),
        ),
        migrations.AddField(
            model_name='genre',
            name='groups',
            field=models.ManyToManyField(help_text='Add groups for this genre.', related_name='_genre_groups_+', to='artist.Group'),
        ),
        migrations.RemoveField(
            model_name='group',
            name='genre',
        ),
        migrations.AddField(
            model_name='group',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Enter a genre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='artist.Genre'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.ManyToManyField(help_text='Select instrument(s) for this musician.', to='artist.Instrument'),
        ),
    ]
