# Generated by Django 3.0.6 on 2020-06-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_auto_20200608_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='about',
            field=models.CharField(default="The genre's description goes here. The genre's description goes here. The genre's description goes here. The genre's description goes here. The genre's description goes here. The genre's description goes here.", max_length=300),
        ),
    ]
