# Generated by Django 3.0.6 on 2020-06-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0015_auto_20200608_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='group',
            name='genre',
        ),
        migrations.AddField(
            model_name='group',
            name='genre',
            field=models.ManyToManyField(help_text='Enter a genre.', to='artist.Genre'),
        ),
    ]
