# Generated by Django 3.0.6 on 2020-06-08 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0016_auto_20200608_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='about',
        ),
    ]
