# Generated by Django 3.0.6 on 2020-06-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0017_remove_genre_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='bio',
        ),
    ]
