# Generated by Django 3.0.6 on 2020-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0018_remove_group_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='about',
            field=models.CharField(default="The genre's description goes here.", max_length=300),
        ),
        migrations.AddField(
            model_name='genre',
            name='groups',
            field=models.ManyToManyField(help_text='Add groups for this genre.', related_name='_genre_groups_+', to='artist.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='bio',
            field=models.CharField(default="The artist's short bio goes here.", max_length=300),
        ),
        migrations.RemoveField(
            model_name='group',
            name='genre',
        ),
        migrations.AddField(
            model_name='group',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='Enter a genre.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='artist.Genre'),
        ),
    ]
