# Generated by Django 3.0.6 on 2020-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0020_auto_20200608_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='photo',
            field=models.CharField(default='https://images.app.goo.gl/ivoQGPgXPHC79EBKA', max_length=200),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.CharField(default='https://images.app.goo.gl/ivoQGPgXPHC79EBKA', max_length=200),
        ),
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.CharField(default='https://images.app.goo.gl/ivoQGPgXPHC79EBKA', max_length=200),
        ),
    ]
