# Generated by Django 3.0.6 on 2020-06-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0021_auto_20200608_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='photo',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/f/f9/Rage_Against_The_Machine.jpg', max_length=200),
        ),
    ]
