# Generated by Django 3.0.6 on 2020-06-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0022_auto_20200608_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a genre (e.g. hip hop, blues, metal, house, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='bio',
            field=models.CharField(default="The artist's bio goes here. The artist's bio goes here. The artist's bio goes here. The artist's bio goes here. The artist's bio goes here.", max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text="Enter the group's name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='origin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(help_text='Enter an instrument (e.g. vocals, synth, guitar, bass, drums)', max_length=100),
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musician',
            name='hometown',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
