# Generated by Django 3.0.6 on 2020-06-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0023_auto_20200609_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='photo2',
            field=models.ImageField(default='https://images.app.goo.gl/ivoQGPgXPHC79EBKA', upload_to='groups'),
        ),
    ]
