# Generated by Django 3.0.6 on 2020-06-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0027_auto_20200610_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='photo2',
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='https://images.app.goo.gl/ivoQGPgXPHC79EBKA', upload_to='groups'),
        ),
    ]
