# Generated by Django 3.0.6 on 2020-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0034_auto_20200612_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(default='/media/bc1.jpg', upload_to='groups/'),
        ),
    ]
