# Generated by Django 3.0.6 on 2020-06-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0037_auto_20200615_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(default=1980),
        ),
    ]
