# Generated by Django 3.0.6 on 2020-06-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0038_auto_20200615_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='date_formed',
        ),
        migrations.AddField(
            model_name='group',
            name='year_formed',
            field=models.IntegerField(default=1980),
        ),
    ]
