# Generated by Django 3.0.6 on 2020-06-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0039_auto_20200615_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='bio',
            field=models.CharField(default="The artist's bio goes here. The artist's bio goes here. The artist's bio goes here. The artist's bio goes here. The artist's bio goes here.", max_length=2000),
        ),
    ]
