# Generated by Django 3.0.6 on 2020-06-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0040_auto_20200615_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(default='/media/bc1.jpg', upload_to='musicians/'),
        ),
    ]
