# Generated by Django 3.0.6 on 2020-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0041_auto_20200616_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='alias',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
    ]
