# Generated by Django 3.0.6 on 2020-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0042_musician_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='alias',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
