# Generated by Django 3.0.6 on 2020-06-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0044_auto_20200620_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['release_year']},
        ),
    ]
