# Generated by Django 3.0.6 on 2020-06-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0045_auto_20200620_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='group',
            name='logo',
            field=models.ImageField(default='media/bc1.jpg', upload_to='groups/'),
        ),
    ]
