# Generated by Django 3.0.6 on 2020-06-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0046_auto_20200621_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='bio',
            field=models.CharField(default="The musician's bio goes here. Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.", max_length=2000),
        ),
    ]
