# Generated by Django 3.0.6 on 2020-06-24 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0047_musician_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['alias', 'first_name', 'last_name']},
        ),
    ]
