# Generated by Django 3.0.6 on 2020-06-24 15:26

from django.db import migrations, models
import music.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0048_auto_20200624_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(storage=music.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
